name: learn-github-actions
on: [push]
jobs:
  execute-gradle-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: run tests
        run:  ./gradlew test
