name: learn-github-actions
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        boot-version: ["2.2.6.RELEASE", "2.3.6.RELEASE", "2.4.0"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: run tests
        run:  SpringBootVersion=${{ matrix.boot-version }} ./gradlew test -i
