name: learn-github-actions
on: [push]
jobs:
  run-tests:
    runs-on: Ubuntu-20.04
    strategy:
      matrix:
        boot-version: ["2.2.6.RELEASE", "2.3.6.RELEASE"]
        java-version: ["1.8", "11"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: run tests
        run:  SpringBootVersion=${{ matrix.boot-version }} JavaVersion=${{ matrix.java-version }} ./gradlew test -i
